//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficialPSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRequests
    {
        public int aid { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<int> status { get; set; }
        public string message { get; set; }
    
        public virtual users users { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
