//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficialPSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupRequests
    {
        public int message_id { get; set; }
        public string message_body { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual group group { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
