//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficialPSAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.projectRequests = new HashSet<projectRequests>();
        }
    
        public int pid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> thresholdCgpa { get; set; }
    
        public virtual group group { get; set; }
        public virtual projectDomain projectDomain { get; set; }
        public virtual users users { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectRequests> projectRequests { get; set; }
    }
}
